import React,{Component}from"react";
import intlTelInput from"intl-tel-input";
// Defines window.intlTelInputUtils. Required for getNumber()/formatOnDisplay/placeholders;
// the legacy Dojo widget loaded the same file as an AMD dependency.
import"intl-tel-input/build/js/utils";
import{init}from"./util.js";
import"../ui/intl-tel-input/intlTelInput.css";
const i=init();
export class InternationalPhoneComponent extends Component{
	constructor(props){
		super(props);
		this.onBlur=this.onBlur.bind(this);
		// We decorate the Mendix text box dropped into our content zone rather than
		// rendering our own input, so the ref is on the container and we look inside it.
		this.containerRef=React.createRef();
		this.input=null;
		this.iti=null;
		window.wcom=this;
		window.intlTelInput=intlTelInput;
	}
	componentDidMount(){
		const input=this.containerRef.current?this.containerRef.current.querySelector("input"):null;
		if(input==null)return;
		this.input=input;
		var excludeCountries=[];
		for(var i=0;i<this.props.excludeCountries.length;i++){
			excludeCountries.push(this.props.excludeCountries[i].country);
		}
		var localizedCountries={};
		for(var i=0;i<this.props.localizedCountries.length;i++){
			localizedCountries[this.props.localizedCountries[i].country]=this.props.localizedCountries[i].translation;
		}
		var onlyCountries=[];
		for(var i=0;i<this.props.onlyCountries.length;i++){
			onlyCountries.push(this.props.onlyCountries[i].country);
		}
		var preferredCountries=[];
		for(var i=0;i<this.props.preferredCountries.length;i++){
			preferredCountries.push(this.props.preferredCountries[i].country);
		}
		this.iti=intlTelInput(input,{
			allowDropdown:this.props.allowDropdown,
			autoHideDialCode:this.props.autoHideDialCode,
			autoPlaceholder:this.props.autoPlaceholder,
			//Type: Array Default: undefined
			//In the dropdown, display all countries except the ones you specify here.
			excludeCountries:excludeCountries,
			//Type: Boolean Default: true
			//Format the input value (according to the nationalMode option) during initialisation, and on setNumber. Requires the utilsScript option.
			formatOnDisplay:this.props.formatOnDisplay,
			//Type: String Default: ""
			//Set the initial country selection by specifying its country code. You can also set it to "auto", which will lookup the user's country based on their IP address (requires the geoIpLookup option - see example). Note that the "auto" option will not update the country selection if the input already contains a number.
			//If you leave initialCountry blank, it will default to the first country in the list
			initialCountry:this.props.initialCountry,
			//Type: Object Default:{}
			//Allows to translate the countries by its given iso code e.g.:
			//{"de":"Deutschland"}
			localizedCountries:localizedCountries,
			//Type: Boolean Default: true
			//Allow users to enter national numbers (and not have to think about international dial codes). Formatting, validation and placeholders still work. Then you can use getNumber to extract a full international number - see example. This option now defaults to true, and it is recommended that you leave it that way as it provides a better experience for the user.
			nationalMode:this.props.nationalMode,
			//Type: Array Default: undefined
			//In the dropdown, display only the countries you specify - see example.
			onlyCountries:onlyCountries,
			//Type: String Default: "MOBILE"
			//Specify one of the keys from the global enum intlTelInputUtils.numberType e.g. "FIXED_LINE" to set the number type to use for the placeholder.
			placeholderNumberType:this.props.placeholderNumberType,
			//Type: Array Default: ["us", "gb"]
			//Specify the countries to appear at the top of the list.
			preferredCountries:preferredCountries,
			//Type: Boolean Default: false
			//Display the country dial code next to the selected flag so it's not part of the typed number. Note that this will disable nationalMode because technically we are dealing with international numbers, but with the dial code separated.
			separateDialCode:this.props.separateDialCode,
			//Type: Function Default: null
			//Change the placeholder generated by autoPlaceholder. Must return a string.
			customPlaceholder:function(selectedCountryPlaceholder,selectedCountryData){
				return"e.g. "+selectedCountryPlaceholder;
			},
			//dropdownContainer
			//Type: Node Default: null
			//Expects a node e.g. document.body. Instead of putting the country dropdown next to the input, append it to the specified node, and it will then be positioned absolutely next to the input using JavaScript. This is useful when the input is inside a container with overflow: hidden. Note that the absolute positioning can be broken by scrolling, so it will automatically close on the window scroll event.
			dropdownContainer:null,
			//Type: Function Default: null
			//When setting initialCountry to "auto", you must use this option to specify a custom function that looks up the user's location, and then calls the success callback with the relevant country code. Also note that when instantiating the plugin, if the Promise object is defined, one of those is returned under the promise instance property, so you can do something like iti.promise.then(callback) to know when initialisation requests like this have completed.
			geoIpLookup:null,
			//Type: String Default: ""
			//Add a hidden input with the given name.
			hiddenInput:"",
		});
		this.input.addEventListener("blur",this.onBlur);
		this.iti.telInput.addEventListener("countrychange",()=>{
			//this.setState({value:"+"+this.iti.selectedCountryData.iso2});
			this.props.setIso2(this.iti.selectedCountryData.iso2,(format)=>this.getFormattedNumber(format));
		});
	}
	componentWillUnmount(){
		if(this.input!=null){
			this.input.removeEventListener("blur",this.onBlur);
		}
		if(this.iti!=null){
			this.iti.destroy();
		}
	}
	// The Mendix text box owns its own value binding, but the country selection is ours.
	// intlTelInput only reads initialCountry once, at init, so without this the flag never
	// follows the attribute changing later (a microflow writing it, or the data view moving
	// to a different record).
	componentDidUpdate(prevProps){
		if(this.iti==null)return;
		const next=this.props.initialCountry;
		if(!next||next===prevProps.initialCountry)return;
		const current=this.iti.selectedCountryData?this.iti.selectedCountryData.iso2:null;
		// Compare case-insensitively: the attribute may hold "US" while iso2 is "us".
		// Skipping the no-op call also stops setCountry -> countrychange -> setValue looping.
		if(current&&current.toLowerCase()===String(next).toLowerCase())return;
		this.iti.setCountry(String(next).toLowerCase());
	}
	// Resolve the current number in one of intl-tel-input's formats.
	// Mirrors the legacy widget: iti.getNumber(intlTelInputUtils.numberFormat[<FORMAT>]).
	getFormattedNumber(format){
		if(this.iti==null)return"";
		const formats=(typeof window!=="undefined"&&window.intlTelInputUtils)?window.intlTelInputUtils.numberFormat:null;
		if(formats==null||formats[format]===undefined)return this.iti.getNumber();
		return this.iti.getNumber(formats[format]);
	}
	onBlur(){
		if(this.input==null)return;
		// Pass the selected country too. countrychange does not fire reliably -- it is
		// driven by keyup, so a value set programmatically (Mendix re-rendering the bound
		// text box) changes the number without ever firing it, leaving the country
		// attribute stale. The legacy widget wrote the country on blur for this reason.
		const iso2=(this.iti&&this.iti.selectedCountryData)?this.iti.selectedCountryData.iso2:null;
		this.props.onChange(this.input.value,(format)=>this.getFormattedNumber(format),iso2);
	}
	render(){
		// Render only the drop zone. The text box inside keeps every stock Mendix
		// property -- label, editability, validation, accessibility, events.
		return(
			<div className="widget-internationalphone" ref={this.containerRef}>
				{this.props.content}
			</div>
		);
	}
}
