import React,{Component,createElement}from"react";
import intlTelInput from "intl-tel-input";
//import"intl-tel-input/build/css/intlTelInput.css";
import"../ui/intl-tel-input/intlTelInput.css";
import{init}from"./util.js";
const i=init();
export class InternationalPhoneComponent extends Component{
	constructor(props){
		super(props);
		this.state={
			value:props.value,
			displayValue:"",
			mask:"999-999"
		};
		this.onChange=this.onChange.bind(this);
		this.onBlur=this.onBlur.bind(this);
		this.onKeyUp=this.onKeyUp.bind(this);
		this.inputRef=React.createRef();
		this.iti=null;
		window.wcom=this;
		window.intlTelInput=intlTelInput;
	}
	componentDidMount(){
		let input=this.inputRef.current;
		var excludeCountries=[];
		for(var i=0;i<this.props.excludeCountries.length;i++){
			excludeCountries.push(this.excludeCountries[i].country);
		}
		var localizedCountries={};
		for(var i=0;i<this.props.localizedCountries.length;i++){
			localizedCountries[this.props.localizedCountries[i].country]=this.props.localizedCountries[i].translation;
		}
		var onlyCountries=[];
		for(var i=0;i<this.props.onlyCountries.length;i++){
			onlyCountries.push(this.props.onlyCountries[i].country);
		}
		var preferredCountries=[];
		for(var i=0;i<this.props.preferredCountries.length;i++){
			preferredCountries.push(this.props.preferredCountries[i].country);
		}
console.error("this.props.formatOnDisplay");
console.error(this.props.formatOnDisplay);
console.error("this.props.nationalMode");
console.error(this.props.nationalMode);
		this.iti=intlTelInput(input,{
			allowDropdown:this.props.allowDropdown,
			autoHideDialCode:this.props.autoHideDialCode,
			autoPlaceholder:this.props.autoPlaceholder,
			//Type: Array Default: undefined
			//In the dropdown, display all countries except the ones you specify here.
			excludeCountries:excludeCountries,
			//Type: Boolean Default: true
			//Format the input value (according to the nationalMode option) during initialisation, and on setNumber. Requires the utilsScript option.
			formatOnDisplay:this.props.formatOnDisplay,
			//Type: String Default: ""
			//Set the initial country selection by specifying its country code. You can also set it to "auto", which will lookup the user's country based on their IP address (requires the geoIpLookup option - see example). Note that the "auto" option will not update the country selection if the input already contains a number.
			//If you leave initialCountry blank, it will default to the first country in the list
			initialCountry:this.props.initialCountry,
			//Type: Object Default:{}
			//Allows to translate the countries by its given iso code e.g.:
			//{"de":"Deutschland"}
			localizedCountries:this.props.localizedCountries,
			//Type: Boolean Default: true
			//Allow users to enter national numbers (and not have to think about international dial codes). Formatting, validation and placeholders still work. Then you can use getNumber to extract a full international number - see example. This option now defaults to true, and it is recommended that you leave it that way as it provides a better experience for the user.
			nationalMode:this.props.nationalMode,
			//Type: Array Default: undefined
			//In the dropdown, display only the countries you specify - see example.
			onlyCountries:onlyCountries,
			//Type: String Default: "MOBILE"
			//Specify one of the keys from the global enum intlTelInputUtils.numberType e.g. "FIXED_LINE" to set the number type to use for the placeholder.
			placeholderNumberType:this.props.placeholderNumberType,
			//Type: Array Default: ["us", "gb"]
			//Specify the countries to appear at the top of the list.
			preferredCountries:this.props.preferredCountries,
			//Type: Boolean Default: false
			//Display the country dial code next to the selected flag so it's not part of the typed number. Note that this will disable nationalMode because technically we are dealing with international numbers, but with the dial code separated.
			separateDialCode:this.props.separateDialCode,
			//Type: Function Default: null
			//Change the placeholder generated by autoPlaceholder. Must return a string.
			customPlaceholder:function(selectedCountryPlaceholder,selectedCountryData){
				return"e.g. "+selectedCountryPlaceholder;
			},
			//dropdownContainer
			//Type: Node Default: null
			//Expects a node e.g. document.body. Instead of putting the country dropdown next to the input, append it to the specified node, and it will then be positioned absolutely next to the input using JavaScript. This is useful when the input is inside a container with overflow: hidden. Note that the absolute positioning can be broken by scrolling, so it will automatically close on the window scroll event.
			dropdownContainer:null,
			//Type: Function Default: null
			//When setting initialCountry to "auto", you must use this option to specify a custom function that looks up the user's location, and then calls the success callback with the relevant country code. Also note that when instantiating the plugin, if the Promise object is defined, one of those is returned under the promise instance property, so you can do something like iti.promise.then(callback) to know when initialisation requests like this have completed.
			geoIpLookup:null,
			//Type: String Default: ""
			//Add a hidden input with the given name.
			hiddenInput:"",
		});
		this.iti.telInput.addEventListener("countrychange",()=>{
			//this.setState({value:"+"+this.iti.selectedCountryData.iso2});
			this.props.setIso2(this.iti.selectedCountryData.iso2);
		});
	}
	componentWillUnmount(){
		if(this.iti!=null){
			this.iti.destroy();
		}
	}
	componentDidUpdate(prvprops,prvstate){
		if(
			prvprops.value!=null&&
			this.props.value!=null&&
			prvprops.value!=this.props.value
		){
			this.setState({value:this.props.value});
		}
	}
	onChange(event){
		let value=event.target.value;
		this.setState({value:value});
	}
	onKeyUp(event){
	}
	onBlur(event){
		this.onChange(event);
		let value=event.target.value;
		this.props.onChange(value);
	}
	render(){
		return(
			<div
				className={this.props.validation?"widget-internationalphone has-error":"widget-internationalphone"}
			>
					<input
						className="form-control"
						value={this.state.value}
						onChange={this.onChange}
						onKeyUp={this.onKeyUp}
						onBlur={this.onBlur}
						ref={this.inputRef}
					>
					</input>
					{
						this.props.validation?(
							<div
								className="alert alert-danger mx-validation-message"
							>
								{this.props.validation}
							</div>
						):(null)
					}
			</div>
		);
	}
}
